/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import nucleo.ArvoreBinaria;

/**
 *
 * @author Yan Kaic
 */
public class FormGUI extends javax.swing.JFrame {

  ArvoreBinaria arvore;

  /**
   * Creates new form FormGUI
   */
  public FormGUI() {
    this.arvore = new ArvoreBinaria();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    campoEntrada = new javax.swing.JTextField();
    botaoAdicionar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    painelArvore = arvore.getVisual();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridLayout(1, 0, 3, 3));

    campoEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        campoEntradaMouseClicked(evt);
      }
    });
    campoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        campoEntradaKeyPressed(evt);
      }
    });
    jPanel1.add(campoEntrada);

    botaoAdicionar.setText("Adicionar");
    botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botaoAdicionarActionPerformed(evt);
      }
    });
    jPanel1.add(botaoAdicionar);

    painelArvore.setBackground(new java.awt.Color(255, 255, 255));
    painelArvore.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    javax.swing.GroupLayout painelArvoreLayout = new javax.swing.GroupLayout(painelArvore);
    painelArvore.setLayout(painelArvoreLayout);
    painelArvoreLayout.setHorizontalGroup(
      painelArvoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 727, Short.MAX_VALUE)
    );
    painelArvoreLayout.setVerticalGroup(
      painelArvoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 352, Short.MAX_VALUE)
    );

    jScrollPane1.setViewportView(painelArvore);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
    inserirValor();
  }//GEN-LAST:event_botaoAdicionarActionPerformed

  private void campoEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEntradaKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      inserirValor();
    }
  }//GEN-LAST:event_campoEntradaKeyPressed

  public void inserirValor() {
    try {
      int valor = Integer.parseInt(campoEntrada.getText());
      arvore.inserir(valor);
      campoEntrada.setText("");
    }
    catch (IllegalArgumentException error) {
      JOptionPane.showMessageDialog(this, error.getMessage(), "Erro!", JOptionPane.WARNING_MESSAGE);
    }
  }

  private void campoEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoEntradaMouseClicked
    campoEntrada.setText("");
  }//GEN-LAST:event_campoEntradaMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botaoAdicionar;
  private javax.swing.JTextField campoEntrada;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel painelArvore;
  // End of variables declaration//GEN-END:variables
}
